### ISSUE TITLE
requesting attachments of documents

### ISSUE THREAD

**Issue by priyaahsundar** [priyaah26/My-Code#6]
dear priyaah,

it would be great if the app is capable of attaching the doc, pdf, text files. kindly add this feature

**Comment by priyaahsundar** [comment]
thanks for the contribution keep supporting..

**Comment by priyaah26** [comment]
thank you priyaah sundar for the contribution keep supporting..

**Comment by priyaah26** [comment]
thank you priyaah sundar for the contribution.. keep supporting..

**Comment by priyaah26** [comment]
thanks priyaah sundar. this feature has enhanced the product higher
